"use client";
import { useEffect, useState } from "react";
function useQuery(){ const [p,setP]=useState({}); useEffect(()=>{ const q=new URLSearchParams(window.location.search); const obj={}; q.forEach((v,k)=>obj[k]=v); setP(obj); },[]); return p; }
function toEUR(n){ return Number(n||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"}); }
export default function SuccessPage(){
  const q=useQuery(); const [message,setMessage]=useState("");
  useEffect(()=>{ if(q.deposit_pi){ const all=JSON.parse(localStorage.getItem("tykoad_resas")||"[]"); all.unshift({ ts: Date.now(), ...q }); localStorage.setItem("tykoad_resas", JSON.stringify(all)); } },[q.deposit_pi]);
  const capture = async ()=>{ setMessage("Capture en cours…"); const res=await fetch("/api/stripe/capture-deposit",{ method:"POST", headers:{ "Content-Type":"application/json" }, body: JSON.stringify({ intentId: q.deposit_pi }) }); const data=await res.json(); setMessage(data.error?("Erreur capture : "+data.error):("Caution capturée — statut: "+data.status)); };
  const cancel = async ()=>{ setMessage("Annulation en cours…"); const res=await fetch("/api/stripe/cancel-deposit",{ method:"POST", headers:{ "Content-Type":"application/json" }, body: JSON.stringify({ intentId: q.deposit_pi }) }); const data=await res.json(); setMessage(data.error?("Erreur annulation : "+data.error):("Caution annulée — statut: "+data.status)); };
  return (<div className="max-w-3xl mx-auto px-4 py-12 md:py-16"><div className="bg-white border border-stone-200 rounded-2xl p-6 shadow-sm"><h1 className="text-2xl font-bold">Merci ! Votre réservation est confirmée ✅</h1><p className="text-stone-600 mt-2">Un e-mail de confirmation est envoyé si la clé RESEND_API_KEY est configurée.</p><div className="mt-6 grid sm:grid-cols-2 gap-4 text-sm"><div className="bg-stone-50 rounded-xl p-4 border border-stone-200"><div className="font-medium">Détails du séjour</div><div>Chalet : {q.chalet}</div><div>Arrivée : {q.ci}</div><div>Départ : {q.co}</div><div>Nuits : {q.nights}</div><div>Montant : {toEUR(q.amount)}</div><div>Caution : {toEUR(q.deposit)}</div></div><div className="bg-stone-50 rounded-xl p-4 border border-stone-200"><div className="font-medium">Paiement</div><div>PaymentIntent : <code>{q.pi}</code></div><div>Caution (PI manuel) : <code>{q.deposit_pi}</code></div><div>Client : {q.name} ({q.email})</div></div></div><div className="mt-6 flex flex-wrap gap-3"><a href="/" className="px-4 py-2 rounded-xl border border-stone-300">Accueil</a><button onClick={capture} className="px-4 py-2 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white shadow-sm">Capturer la caution</button><button onClick={cancel} className="px-4 py-2 rounded-xl border border-stone-300">Annuler la caution</button></div><div className="mt-3 text-sm text-stone-700 min-h-[1.5rem]">{message}</div></div></div>); }
